#!/usr/bin/env python3
"""
Generate static HTML link lists so crawlers can discover all 17k CPT pages.

Without this, every individual CPT detail page is orphaned: category pages
render their listings client-side from JSON, so Googlebot sees an empty
<div id="cpt-codes-list"> and has no <a href> tags to follow. The result is
~11k URLs stuck in "Discovered - currently not indexed" forever.

This script produces three outputs:

  1. _includes/cpt-static-list-<category>.html
     One include per category. Injected into each category's index.html
     as a server-rendered <ul> of every code in that category.

  2. cpt-codes/all/index.html
     A master HTML sitemap: every code, grouped by category. Acts as a
     high-equity link hub that flows PageRank to every individual page.

  3. Patches the 20 category index.html files to include their static
     list (idempotent — safe to re-run).

Usage:
    python3 _scripts/generate-cpt-link-hub.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "data/cpt-codes.json"
INCLUDES_DIR = ROOT / "_includes"
CPT_ROOT = ROOT / "cpt-codes"
INCLUDE_MARKER = "<!-- CPT_STATIC_LIST_INJECTED -->"


def escape(s: str | None) -> str:
    if s is None:
        return ""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def group_by_category(data: list[dict]) -> tuple[dict[str, list[dict]], dict[str, str]]:
    by_cat: dict[str, list[dict]] = {}
    cat_names: dict[str, str] = {}
    for entry in data:
        cat = entry.get("cat")
        if not cat:
            continue
        by_cat.setdefault(cat, []).append(entry)
        if cat not in cat_names and entry.get("cd"):
            cat_names[cat] = entry["cd"]
    for codes in by_cat.values():
        codes.sort(key=lambda x: x.get("c", ""))
    return by_cat, cat_names


def heading(display: str, count: int) -> str:
    """'All 5,933 Surgery Codes' but 'All 3 R Codes' (avoid duplicate 'Codes')."""
    if "code" in display.lower():
        return f"All {count:,} {display}"
    return f"All {count:,} {display} Codes"


def write_category_includes(by_cat, cat_names):
    INCLUDES_DIR.mkdir(exist_ok=True)
    for cat, codes in by_cat.items():
        display = cat_names.get(cat, cat)
        lines = [
            "<!-- AUTO-GENERATED by _scripts/generate-cpt-link-hub.py -->",
            f'<section class="cpt-all-codes" aria-label="{escape(heading(display, len(codes)))}">',
            f"  <h2>{escape(heading(display, len(codes)))}</h2>",
            '  <ul class="cpt-all-codes-list">',
        ]
        for code in codes:
            c = escape(code.get("c", ""))
            d = escape(code.get("d", ""))
            url = f"/cpt-codes/{cat}/{c}/"
            lines.append(f'    <li><a href="{url}"><strong>{c}</strong> &mdash; {d}</a></li>')
        lines.append("  </ul>")
        lines.append("</section>")
        out = INCLUDES_DIR / f"cpt-static-list-{cat}.html"
        out.write_text("\n".join(lines) + "\n")
        print(f"  wrote {out.relative_to(ROOT)}  ({len(codes):,} codes)")


def write_master_hub(by_cat, cat_names):
    total = sum(len(codes) for codes in by_cat.values())
    lines = [
        "---",
        "layout: default",
        f'title: "All {total:,} CPT &amp; HCPCS Codes — Complete Index | RVU Edge"',
        f'description: "Complete A-Z index of {total:,} CPT and HCPCS codes with wRVU values and descriptions. Browse every code by category."',
        "---",
        "",
        '<main class="cpt-all-hub max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 pt-28">',
        '  <nav class="cpt-detail-breadcrumbs" aria-label="Breadcrumb">',
        '    <a href="/cpt-codes/">CPT Codes</a>',
        '    <span class="sep">/</span>',
        '    <span class="current">All Codes</span>',
        "  </nav>",
        f"  <h1>All {total:,} CPT &amp; HCPCS Codes</h1>",
        '  <p class="cpt-hub-intro">Complete index of every CPT and HCPCS code covered on RVU Edge, grouped by category. Click any code for full wRVU data, Medicare payment estimates, and clinical context.</p>',
        "",
        '  <nav class="cpt-hub-toc" aria-label="Jump to category">',
        "    <strong>Jump to category:</strong>",
    ]

    ordered_cats = sorted(by_cat.keys(), key=lambda c: -len(by_cat[c]))
    toc_items = []
    for cat in ordered_cats:
        display = cat_names.get(cat, cat)
        toc_items.append(f'<a href="#{cat}">{escape(display)} ({len(by_cat[cat]):,})</a>')
    lines.append("    " + " &middot; ".join(toc_items))
    lines.append("  </nav>")
    lines.append("")

    for cat in ordered_cats:
        codes = by_cat[cat]
        display = cat_names.get(cat, cat)
        lines.append(f'  <section class="cpt-hub-category" id="{cat}">')
        lines.append(
            f'    <h2><a href="/cpt-codes/{cat}/">{escape(display)}</a> '
            f'<span class="cpt-hub-count">({len(codes):,} codes)</span></h2>'
        )
        lines.append('    <ul class="cpt-all-codes-list">')
        for code in codes:
            c = escape(code.get("c", ""))
            d = escape(code.get("d", ""))
            url = f"/cpt-codes/{cat}/{c}/"
            lines.append(f'      <li><a href="{url}"><strong>{c}</strong> &mdash; {d}</a></li>')
        lines.append("    </ul>")
        lines.append("  </section>")

    lines.append("</main>")

    out_dir = CPT_ROOT / "all"
    out_dir.mkdir(exist_ok=True)
    out = out_dir / "index.html"
    out.write_text("\n".join(lines) + "\n")
    size_mb = out.stat().st_size / 1024 / 1024
    print(f"  wrote {out.relative_to(ROOT)}  ({total:,} codes, {size_mb:.1f} MB)")


def inject_includes_into_category_pages(by_cat):
    for cat in by_cat:
        cat_index = CPT_ROOT / cat / "index.html"
        if not cat_index.exists():
            print(f"  skip {cat}: no index.html")
            continue
        text = cat_index.read_text()
        if INCLUDE_MARKER in text:
            continue  # idempotent: already injected
        snippet = f"\n  {INCLUDE_MARKER}\n  {{% include cpt-static-list-{cat}.html %}}\n"
        if "</main>" not in text:
            print(f"  WARN {cat_index.relative_to(ROOT)}: no </main> tag, skipped")
            continue
        # Inject just before the first </main>
        text = text.replace("</main>", snippet + "</main>", 1)
        cat_index.write_text(text)
        print(f"  injected into {cat_index.relative_to(ROOT)}")


def main() -> int:
    data = json.loads(DATA_FILE.read_text())
    by_cat, cat_names = group_by_category(data)
    total = sum(len(v) for v in by_cat.values())
    print(f"Loaded {total:,} codes across {len(by_cat)} categories\n")

    print("1. Per-category include files:")
    write_category_includes(by_cat, cat_names)

    print("\n2. Master HTML sitemap hub:")
    write_master_hub(by_cat, cat_names)

    print("\n3. Injecting includes into category pages:")
    inject_includes_into_category_pages(by_cat)

    print("\nDone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
